<x-workspace-shell role="client" title="Offers & applications" eyebrow="Client workspace">
    <div class="mx-auto max-w-6xl">
        <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="sl-kicker">Compare with confidence</p><h2 class="mt-2 text-4xl font-bold tracking-tight text-[var(--ink)]">Freelancer offers</h2><p class="mt-2 text-[var(--muted)]">Review proposals and choose the right person for each mission.</p></div><span class="rounded-full bg-blue-50 px-3 py-2 text-xs font-bold text-[var(--blue)]">{{ $applications->where('status', 'pending')->count() }} pending review</span></div>
        <div class="mt-7 flex gap-2 overflow-x-auto border-b border-[var(--line)] pb-3"><span class="rounded-full bg-blue-50 px-4 py-2 text-xs font-bold text-[var(--blue)]">All offers</span><span class="rounded-full px-4 py-2 text-xs font-bold text-[var(--muted)]">Pending</span><span class="rounded-full px-4 py-2 text-xs font-bold text-[var(--muted)]">Accepted</span><span class="rounded-full px-4 py-2 text-xs font-bold text-[var(--muted)]">Rejected</span></div>
        <div class="mt-6 space-y-7">
            @forelse($applications->groupBy('mission_id') as $missionApplications)
                @php($mission = $missionApplications->first()->mission)
                <section class="sl-panel overflow-hidden"><div class="flex flex-col justify-between gap-3 border-b border-[var(--line)] bg-slate-50/70 p-5 sm:flex-row sm:items-center sm:px-6"><div><p class="text-xs font-bold uppercase tracking-wider text-[var(--blue)]">{{ $mission->category?->name ?? 'Mission' }}</p><h3 class="mt-1 text-xl font-bold text-[var(--ink)]">{{ $mission->title }}</h3></div><div class="text-sm text-[var(--muted)]">{{ $missionApplications->count() }} offers · Budget {{ number_format($mission->budget, 2) }} MAD</div></div><div class="divide-y divide-[var(--line)]">@foreach($missionApplications as $application)<article class="p-5 sm:p-6 {{ $application->status === 'accepted' ? 'bg-emerald-50/50' : '' }}"><div class="flex flex-col gap-5 lg:flex-row lg:items-start"><div class="flex min-w-0 flex-1 gap-3"><span class="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-[var(--ink)] font-bold text-white">{{ strtoupper(substr($application->freelance->name, 0, 1)) }}</span><div><div class="flex flex-wrap items-center gap-2"><h4 class="font-bold text-[var(--ink)]">{{ $application->freelance->name }}</h4><span class="rounded-full px-2 py-1 text-[10px] font-bold uppercase {{ $application->status === 'accepted' ? 'bg-emerald-100 text-emerald-700' : ($application->status === 'rejected' ? 'bg-red-50 text-red-600' : 'bg-amber-50 text-amber-700') }}">{{ $application->status }}</span></div><p class="mt-1 text-xs text-[var(--muted)]">{{ $application->freelance->email }} · Freelancer</p></div></div><div class="lg:text-right"><p class="text-2xl font-bold text-[var(--ink)]">{{ number_format($application->proposed_price, 2) }} <span class="text-sm font-semibold text-[var(--muted)]">MAD</span></p><p class="mt-1 text-xs text-[var(--muted)]">Submitted {{ $application->date_submission?->diffForHumans() ?? $application->created_at->diffForHumans() }}</p></div></div><div class="mt-5 grid gap-4 lg:grid-cols-[1fr_auto] lg:items-end"><p class="rounded-2xl bg-slate-50 p-4 text-sm leading-6 text-[var(--muted)]">{{ $application->cover_letter }}</p>@if($application->status === 'pending')<div class="flex flex-wrap gap-2"><form method="POST" action="{{ route('client.applications.accept', $application) }}">@csrf<button class="sl-button-primary">Accept offer</button></form><form method="POST" action="{{ route('client.applications.reject', $application) }}">@csrf<button class="sl-button rounded-xl border border-red-200 bg-red-50 px-4 py-2 text-sm font-bold text-red-700">Reject</button></form></div>@elseif($application->status === 'accepted')<a href="{{ route('missions.show', $mission) }}" class="sl-button-secondary">Manage mission →</a>@endif</div></article>@endforeach</div></section>
            @empty
                <div class="sl-panel p-14 text-center"><span class="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-blue-50 text-2xl text-[var(--blue)]">↗</span><h3 class="mt-5 text-lg font-bold text-[var(--ink)]">No offers yet</h3><p class="mt-2 text-sm text-[var(--muted)]">Publish a mission and freelancer proposals will appear here.</p><a href="{{ route('missions.create') }}" class="sl-button-primary mt-5">Create a mission</a></div>
            @endforelse
        </div>
    </div>
</x-workspace-shell>
