<x-workspace-shell role="freelance" title="Find missions" eyebrow="Freelancer workspace">
    <div class="mx-auto max-w-7xl">
        <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="sl-kicker">Opportunity board</p><h2 class="mt-2 text-4xl font-bold tracking-tight text-[var(--ink)]">Find missions</h2><p class="mt-2 text-[var(--muted)]">Discover missions that match your skills.</p></div><span class="rounded-full bg-blue-50 px-3 py-2 text-xs font-bold text-[var(--blue)]">{{ $missions->count() }} opportunities</span></div>
        <form method="GET" action="{{ route('freelance.missions.index') }}" class="mt-7 rounded-2xl border border-[var(--line)] bg-white p-4"><div class="flex flex-col gap-3 lg:flex-row"><div class="flex min-w-0 flex-1 items-center gap-3 rounded-xl border border-[var(--line)] px-4"><span class="text-lg text-[var(--muted)]">⌕</span><input name="search" value="{{ request('search') }}" placeholder="Search missions, skills or keywords..." class="w-full border-0 py-3 text-sm text-[var(--ink)] placeholder:text-slate-400 focus:ring-0"></div><select name="category_id" class="rounded-xl border-[var(--line)] text-sm text-[var(--muted)]"><option value="">All categories</option>@foreach($categories as $category)<option value="{{ $category->id }}" {{ request('category_id') == $category->id ? 'selected' : '' }}>{{ $category->name }}</option>@endforeach</select><input name="min_budget" value="{{ request('min_budget') }}" type="number" min="0" placeholder="Min budget" class="rounded-xl border-[var(--line)] text-sm"><input name="max_budget" value="{{ request('max_budget') }}" type="number" min="0" placeholder="Max budget" class="rounded-xl border-[var(--line)] text-sm"><select name="sort" class="rounded-xl border-[var(--line)] text-sm text-[var(--muted)]"><option value="latest">Latest</option><option value="deadline" {{ request('sort') === 'deadline' ? 'selected' : '' }}>Deadline</option><option value="budget_low" {{ request('sort') === 'budget_low' ? 'selected' : '' }}>Budget: low</option><option value="budget_high" {{ request('sort') === 'budget_high' ? 'selected' : '' }}>Budget: high</option></select><button class="sl-button-primary">Search</button></div><div class="mt-3 flex flex-wrap items-center gap-2 text-xs"><span class="font-bold text-[var(--muted)]">Status:</span>@foreach(['open', 'in_progress', 'completed', 'cancelled'] as $status)<a href="{{ route('freelance.missions.index', array_merge(request()->query(), ['status' => $status])) }}" class="rounded-full px-3 py-1.5 font-bold {{ request('status', 'open') === $status ? 'bg-blue-50 text-[var(--blue)]' : 'bg-slate-50 text-[var(--muted)]' }}">{{ str_replace('_', ' ', ucfirst($status)) }}</a>@endforeach</div></form>
        <div class="mt-7 grid gap-5 lg:grid-cols-2">
            @forelse($missions as $mission)
                <article class="sl-panel group p-6 transition duration-200 hover:-translate-y-0.5 hover:border-blue-200"><div class="flex items-start justify-between gap-4"><div><span class="text-xs font-bold uppercase tracking-wider text-[var(--blue)]">{{ $mission->category?->name ?? 'Open category' }}</span><h3 class="mt-3 text-xl font-bold leading-tight text-[var(--ink)]"><a href="{{ route('freelance.missions.show', $mission) }}" class="hover:text-[var(--blue)]">{{ $mission->title }}</a></h3></div><span class="rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-emerald-700">{{ str_replace('_', ' ', $mission->status) }}</span></div><p class="mt-3 line-clamp-3 text-sm leading-6 text-[var(--muted)]">{{ $mission->description }}</p><div class="mt-6 grid grid-cols-3 gap-3 border-y border-[var(--line)] py-4 text-sm"><div><p class="text-xs text-[var(--muted)]">Budget</p><p class="mt-1 font-bold text-[var(--ink)]">{{ number_format($mission->budget, 2) }} MAD</p></div><div><p class="text-xs text-[var(--muted)]">Deadline</p><p class="mt-1 font-bold text-[var(--ink)]">{{ $mission->deadline }}</p></div><div><p class="text-xs text-[var(--muted)]">Applications</p><p class="mt-1 font-bold text-[var(--ink)]">{{ $mission->applications_count }}</p></div></div><div class="mt-5 flex items-center justify-between gap-3"><div class="flex items-center gap-2"><span class="flex h-8 w-8 items-center justify-center rounded-full bg-[var(--ink)] text-xs font-bold text-white">{{ strtoupper(substr($mission->client->name ?? 'C', 0, 1)) }}</span><span class="text-xs font-semibold text-[var(--muted)]">{{ $mission->client->name ?? 'Client' }}</span></div><a href="{{ route('freelance.missions.show', $mission) }}" class="sl-button-primary px-4 py-2">View mission <span>→</span></a></div></article>
            @empty
                <div class="sl-panel col-span-full p-14 text-center"><span class="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-blue-50 text-2xl text-[var(--blue)]">⌕</span><h3 class="mt-5 text-lg font-bold text-[var(--ink)]">No missions match your search</h3><p class="mt-2 text-sm text-[var(--muted)]">Try adjusting your filters or search terms.</p><a href="{{ route('freelance.missions.index') }}" class="sl-button-secondary mt-5">Clear filters</a></div>
            @endforelse
        </div>
    </div>
</x-workspace-shell>
