<x-app-layout>
    <div class="min-h-[calc(100vh-65px)] bg-[var(--paper)]">
        <div class="mx-auto grid max-w-[1440px] lg:grid-cols-[230px_1fr]">
            <aside class="hidden border-r border-[var(--line)] bg-white px-4 py-7 lg:block">
                <p class="px-3 text-[10px] font-bold uppercase tracking-[.2em] text-[var(--muted)]">Client workspace</p>
                <nav class="mt-4 space-y-1">
                    <a href="{{ route('client.dashboard') }}" class="flex items-center gap-3 rounded-xl bg-blue-50 px-3 py-3 text-sm font-bold text-[var(--blue)]">⌂ <span>Dashboard</span></a>
                    <a href="{{ route('missions.index') }}" class="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-[var(--muted)] hover:bg-slate-50">▤ <span>My Missions</span></a>
                    <a href="{{ route('missions.create') }}" class="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-[var(--muted)] hover:bg-slate-50">＋ <span>Create Mission</span></a>
                    <a href="{{ route('client.applications.index') }}" class="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-[var(--muted)] hover:bg-slate-50">↗ <span>Applications</span></a>
                    <a href="#activity" class="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-[var(--muted)] hover:bg-slate-50">♢ <span>Notifications</span></a>
                    <a href="{{ route('profile.edit') }}" class="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-[var(--muted)] hover:bg-slate-50">◉ <span>Profile</span></a>
                </nav>
                <div class="mt-12 rounded-2xl bg-blue-50 p-4"><p class="text-xs font-bold text-[var(--blue)]">Bring an idea to life</p><p class="mt-2 text-sm leading-6 text-[var(--muted)]">A clear mission is the first step to finding the right skill.</p><a href="{{ route('missions.create') }}" class="mt-4 inline-block text-xs font-bold text-[var(--blue)] underline underline-offset-4">Create a mission →</a></div>
            </aside>

            <main class="min-w-0 px-5 py-7 sm:px-8 lg:px-10 lg:py-10">
                <div class="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p class="sl-kicker">Client workspace</p><h1 class="mt-2 text-3xl font-bold tracking-tight text-[var(--ink)] sm:text-4xl">Welcome back, {{ auth()->user()->name }} <span aria-hidden="true">👋</span></h1><p class="mt-2 text-[var(--muted)]">Let's bring your next idea to life.</p></div><div class="flex gap-3"><a href="{{ route('missions.create') }}" class="sl-button-primary">Create a mission <span>＋</span></a><a href="{{ route('client.applications.index') }}" class="hidden sl-button-secondary sm:inline-flex">Review applications</a></div></div>
                <section class="relative mt-8 overflow-hidden rounded-3xl bg-white p-6 shadow-[0_18px_60px_rgba(23,35,61,.07)] sm:p-8"><div class="absolute right-0 top-0 h-full w-1/3 bg-blue-50 [clip-path:polygon(35%_0,100%_0,100%_100%,0_100%)]"></div><div class="relative max-w-2xl"><p class="text-xs font-bold uppercase tracking-[.2em] text-[var(--blue)]">Mission control</p><h2 class="mt-3 text-2xl font-bold text-[var(--ink)] sm:text-3xl">Make progress visible. Keep great work moving.</h2><p class="mt-3 max-w-lg text-sm leading-6 text-[var(--muted)]">Track every brief, compare offers and stay close to the people turning your goals into results.</p><div class="mt-6 flex flex-wrap gap-2 text-xs font-bold"><span class="rounded-full bg-blue-50 px-3 py-2 text-blue-700">{{ $stats['open'] }} open missions</span><span class="rounded-full bg-emerald-50 px-3 py-2 text-emerald-700">{{ $stats['completed'] }} completed</span></div></div></section>

                <section class="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div class="sl-panel p-5"><p class="text-xs font-bold uppercase tracking-wider text-[var(--muted)]">Total missions</p><p class="mt-3 text-3xl font-bold text-[var(--ink)]">{{ $stats['total'] }}</p><p class="mt-1 text-xs text-[var(--muted)]">All your briefs</p></div><div class="sl-panel p-5"><p class="text-xs font-bold uppercase tracking-wider text-[var(--muted)]">Open missions</p><p class="mt-3 text-3xl font-bold text-[var(--blue)]">{{ $stats['open'] }}</p><p class="mt-1 text-xs text-[var(--muted)]">Looking for a match</p></div><div class="sl-panel p-5"><p class="text-xs font-bold uppercase tracking-wider text-[var(--muted)]">Active missions</p><p class="mt-3 text-3xl font-bold text-amber-600">{{ $stats['in_progress'] }}</p><p class="mt-1 text-xs text-[var(--muted)]">Work in progress</p></div><div class="sl-panel p-5"><p class="text-xs font-bold uppercase tracking-wider text-emerald-600">Offers received</p><p class="mt-3 text-3xl font-bold text-emerald-600">{{ $stats['applications'] }}</p><p class="mt-1 text-xs text-[var(--muted)]">Freelancers interested</p></div></section>

                <div id="activity" class="mt-8 grid gap-7 xl:grid-cols-[1.35fr_.8fr]"><section><div class="mb-4 flex items-center justify-between"><div><p class="sl-kicker">Your pipeline</p><h2 class="mt-1 text-2xl font-bold text-[var(--ink)]">Recent missions</h2></div><a href="{{ route('missions.index') }}" class="text-sm font-bold text-[var(--blue)]">View all →</a></div><div class="space-y-4">@forelse($recentMissions as $mission)<article class="sl-panel p-5 sm:p-6"><div class="flex items-start justify-between gap-4"><div><span class="text-xs font-bold uppercase tracking-wider text-[var(--blue)]">{{ $mission->category?->name ?? 'Open category' }}</span><h3 class="mt-2 text-lg font-bold text-[var(--ink)]">{{ $mission->title }}</h3></div><span class="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold uppercase tracking-wide text-blue-700">{{ str_replace('_', ' ', $mission->status) }}</span></div><p class="mt-2 line-clamp-2 text-sm leading-6 text-[var(--muted)]">{{ $mission->description }}</p><div class="mt-5 flex flex-wrap items-center gap-x-5 gap-y-2 border-t border-[var(--line)] pt-4 text-sm text-[var(--muted)]"><span><strong class="text-[var(--ink)]">{{ $mission->budget }}</strong> budget</span><span>Due {{ $mission->deadline }}</span><a href="{{ route('missions.show', $mission) }}" class="ml-auto font-bold text-[var(--blue)]">Open mission →</a></div></article>@empty<div class="sl-panel p-10 text-center"><p class="text-lg font-bold text-[var(--ink)]">You haven't published any missions yet.</p><p class="mt-2 text-sm text-[var(--muted)]">Your next great collaboration can start with one clear brief.</p><a href="{{ route('missions.create') }}" class="sl-button-primary mt-5">Create your first mission</a></div>@endforelse</div></section>

                    <aside class="space-y-7"><section class="sl-panel p-6"><div class="flex items-center justify-between"><h2 class="text-lg font-bold text-[var(--ink)]">Next actions</h2><span class="h-2 w-2 rounded-full bg-emerald-500"></span></div><div class="mt-4 space-y-3"><a href="{{ route('missions.create') }}" class="flex items-center gap-3 rounded-2xl bg-blue-50 p-4 text-sm font-semibold text-blue-800"><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-white text-[var(--blue)]">＋</span>Publish a new mission</a><a href="{{ route('client.applications.index') }}" class="flex items-center gap-3 rounded-2xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-800"><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-white text-emerald-600">↗</span>Compare received offers</a></div></section><section class="sl-panel p-6"><h2 class="text-lg font-bold text-[var(--ink)]">Mission lifecycle</h2><div class="mt-5 space-y-4"><div class="flex items-center gap-3"><span class="flex h-8 w-8 items-center justify-center rounded-full bg-blue-100 text-xs font-bold text-blue-700">1</span><div><p class="text-sm font-semibold text-[var(--ink)]">Open</p><p class="text-xs text-[var(--muted)]">Freelancers discover your brief</p></div></div><div class="ml-4 h-5 border-l border-dashed border-blue-200"></div><div class="flex items-center gap-3"><span class="flex h-8 w-8 items-center justify-center rounded-full bg-amber-100 text-xs font-bold text-amber-700">2</span><div><p class="text-sm font-semibold text-[var(--ink)]">In progress</p><p class="text-xs text-[var(--muted)]">The right freelancer is working</p></div></div><div class="ml-4 h-5 border-l border-dashed border-blue-200"></div><div class="flex items-center gap-3"><span class="flex h-8 w-8 items-center justify-center rounded-full bg-emerald-100 text-xs font-bold text-emerald-700">3</span><div><p class="text-sm font-semibold text-[var(--ink)]">Completed</p><p class="text-xs text-[var(--muted)]">Validate and leave a review</p></div></div></div></section></aside></div>
+            </main>
+        </div>
+    </div>
+</x-app-layout>
