<x-workspace-shell role="client" title="My missions" eyebrow="Client workspace">
    <div class="mx-auto max-w-7xl">
        <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="sl-kicker">Mission management</p><h2 class="mt-2 text-4xl font-bold tracking-tight text-[var(--ink)]">My missions</h2><p class="mt-2 text-[var(--muted)]">Keep every brief, offer and outcome in one clear place.</p></div><a href="{{ route('missions.create') }}" class="sl-button-primary">Create mission <span>＋</span></a></div>
        @if(session('success'))<div class="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50 px-5 py-4 text-sm font-semibold text-emerald-800">{{ session('success') }}</div>@endif
        <div class="mt-7 flex gap-2 overflow-x-auto border-b border-[var(--line)] pb-3"><span class="rounded-full bg-blue-50 px-4 py-2 text-xs font-bold text-[var(--blue)]">All missions</span><span class="rounded-full px-4 py-2 text-xs font-bold text-[var(--muted)]">Open</span><span class="rounded-full px-4 py-2 text-xs font-bold text-[var(--muted)]">In progress</span><span class="rounded-full px-4 py-2 text-xs font-bold text-[var(--muted)]">Completed</span><span class="rounded-full px-4 py-2 text-xs font-bold text-[var(--muted)]">Cancelled</span></div>
        <div class="mt-6 grid gap-5 lg:grid-cols-2">
            @forelse($missions as $mission)
                <article class="sl-panel p-6"><div class="flex items-start justify-between gap-4"><div><span class="text-xs font-bold uppercase tracking-wider text-[var(--blue)]">{{ $mission->category?->name ?? 'Open category' }}</span><h3 class="mt-3 text-xl font-bold text-[var(--ink)]">{{ $mission->title }}</h3></div><span class="rounded-full bg-blue-50 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-blue-700">{{ str_replace('_', ' ', $mission->status) }}</span></div><p class="mt-3 line-clamp-2 text-sm leading-6 text-[var(--muted)]">{{ $mission->description }}</p><div class="mt-6 grid grid-cols-3 gap-3 border-y border-[var(--line)] py-4 text-sm"><div><p class="text-xs text-[var(--muted)]">Budget</p><p class="mt-1 font-bold text-[var(--ink)]">{{ number_format($mission->budget, 2) }} MAD</p></div><div><p class="text-xs text-[var(--muted)]">Deadline</p><p class="mt-1 font-bold text-[var(--ink)]">{{ $mission->deadline }}</p></div><div><p class="text-xs text-[var(--muted)]">Offers</p><p class="mt-1 font-bold text-[var(--ink)]">{{ $mission->applications_count }}</p></div></div><div class="mt-5 flex flex-wrap gap-2"><a href="{{ route('missions.show', $mission) }}" class="sl-button-primary px-4 py-2">View mission</a><a href="{{ route('client.applications.index') }}" class="sl-button-secondary px-4 py-2">View applications</a><a href="{{ route('missions.edit', $mission) }}" class="sl-button-secondary px-4 py-2">Edit</a><form method="POST" action="{{ route('missions.destroy', $mission) }}">@csrf @method('DELETE')<button class="sl-button rounded-xl border border-red-200 bg-red-50 px-4 py-2 text-sm font-bold text-red-700" onclick="return confirm('Delete this mission?')">Delete</button></form></div></article>
            @empty
                <div class="sl-panel col-span-full p-14 text-center"><span class="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-blue-50 text-2xl text-[var(--blue)]">▤</span><h3 class="mt-5 text-lg font-bold text-[var(--ink)]">You have no missions yet</h3><p class="mt-2 text-sm text-[var(--muted)]">Create your first brief and find the right freelancer.</p><a href="{{ route('missions.create') }}" class="sl-button-primary mt-5">Create your first mission</a></div>
            @endforelse
        </div>
    </div>
</x-workspace-shell>
